Update hyprcast script.

diff --git a/bin/hyprcast b/bin/hyprcast
--- a/bin/hyprcast
+++ b/bin/hyprcast
@@ -7,20 +7,24 @@ sleep 1
 notify-send -h string:wf-recorder:record -t 950 "Recording in:" "<span color='#EA6962' font='20px'><b>1</b></span>"
 sleep 1
 
-path="invalid"
-good_audio_file=/tmp/audio.wav
+output_path="invalid"
+clean_audio_file=/tmp/audio.wav
 noisy_audio_file=/tmp/temp.wav
-video_file=/tmp/temp_video.mkv
+temporary_video_file=/tmp/temp_video.mkv
 
-wf_recorder_pid=0
-ffplay_pid=0
-ffmpeg_pid=0
+wf_recorder_process_id=0
+ffplay_process_id=0
+ffmpeg_audio_process_id=0
 
-# Iterate through all passed arguments
-for arg in "$@"; do
-  if [[ $arg != --* ]]; then
-    path=$arg
-    if [[ ! -e $path ]]; then
+arnndn_models_directory="$HOME/.local/share/arnndn-models"
+
+LOG_FILE="$HOME/.hyprcast.log"
+
+# Parse arguments to find output path
+for argument in "$@"; do
+  if [[ $argument != --* ]]; then
+    output_path=$argument
+    if [[ ! -e $output_path ]]; then
       echo "Path does not exist"
       exit 1
     fi
@@ -28,78 +32,82 @@ for arg in "$@"; do
   fi
 done
 
-if [[ $path == invalid ]]; then
+if [[ $output_path == invalid ]]; then
   echo "Need path!"
   exit 1
 fi
 
-wf-recorder -f $video_file > /dev/null 2>&1 &
-wf_recorder_pid=$!
+# Video
+wf-recorder -f $temporary_video_file >/dev/null 2>$LOG_FILE &
+wf_recorder_process_id=$!
 
-# Iterate through all passed arguments
-for arg in "$@"; do
-  if [[ $arg == --webcam ]]; then
-    ffplay -f v4l2 -i /dev/video0 -x 232 -y 175 > /dev/null 2>&1 &
-    ffplay_pid=$!
-  fi
-done
-
-# Iterate through all passed arguments
-for arg in "$@"; do
-  if [[ $arg == --audio ]]; then
-    # ffmpeg -y -f alsa -i "default" $audio_file > /dev/null 2>&1 &
-    #
+# Capture audio if specified
+for argument in "$@"; do
+  if [[ $argument == --audio ]]; then
     ffmpeg \
       -f pulse \
       -i "default" \
-      -filter_complex 'asplit[a1] [a2]; [a1] arnndn=m=/home/x/src/arnndn-models/bd.rnnn [o1];[a2] arnndn=m=/home/x/src/arnndn-models/lq.rnnn [o2]' \
-      -map '[o1]' -codec:a pcm_s24le "$good_audio_file" \
+      -filter_complex "asplit[a1] [a2]; [a1] arnndn=m=${arnndn_models_directory}/bd.rnnn [o1];[a2] arnndn=m=${arnndn_models_directory}/lq.rnnn [o2]" \
+      -map '[o1]' -codec:a pcm_s24le "$clean_audio_file" \
       -map '[o2]' -codec:a pcm_s24le "$noisy_audio_file" \
-      > /dev/null 2>&1 & disown
-
-    ffmpeg_pid=$!
+      >/dev/null 2>"$LOG_FILE" &
+    disown
+    ffmpeg_audio_process_id=$!
+  elif [[ $argument == --webcam ]]; then
+    ffplay -f v4l2 -i /dev/video0 -x 232 -y 175 >/dev/null 2>"$LOG_FILE" &
+    disown
+    ffplay_process_id=$!
   fi
 done
 
-safe_kill() {
-  if [[ $1 -gt 0 ]] 2> /dev/null; then
+# Function to safely kill processes
+safe_terminate_process() {
+  if [[ $1 -gt 0 ]] 2>/dev/null; then
     kill -15 "$1" 2>/dev/null || :
   fi
 }
 
-# menu
+# Command menu loop
 while true; do
-    read -r -p "(screencast 󰹑 ) " choice
-    case $choice in
-        stop | s)
-          echo "Quitting..."
-            safe_kill $wf_recorder_pid
-            safe_kill $ffplay_pid
-            safe_kill $ffmpeg_pid
-            if [[ $arg == --audio ]]; then
-              ffmpeg -i $good_audio_file -i $video_file -c:v copy -c:a copy "$path/$(date +%Y-%m-%d_%H-%M-%S).mkv" 
-              # Clean temp audio files
-              rm "$good_audio_file"
-              rm "$noisy_audio_file"
-            else
-              ffmpeg -i $video_file -c:v copy -c:a copy "$path/$(date +%Y-%m-%d_%H-%M-%S).mkv" 
-            fi
+  read -r -p "(hyprcast 󰹑 ) " user_input
+  case $user_input in
+  stop | s)
+    echo "Quitting..."
+    safe_terminate_process $wf_recorder_process_id
+    safe_terminate_process $ffplay_process_id
+    safe_terminate_process $ffmpeg_audio_process_id
 
-            # Clean temp video file
-            rm "$video_file"
-            break 
-            ;;
-        paus | p)
-            echo -e "\nPause"
-            ;;
-        help | h)
-            echo -e "\nAvailable commands are:\n" \
-                    "\033[33mstop\033[0m: recording\n" \
-                    "\033[33mhelp\033[0m: print menu help"
-            ;;
-        *)
-            echo -e "\nInvalid command."
-            ;;
-    esac
+    if [[ $ffmpeg_audio_process_id -ne 0 ]]; then
+      # Merge the audio with the video
+      ffmpeg -i $clean_audio_file -i $temporary_video_file "$output_path/$(date +%Y-%m-%d_%H-%M-%S).mkv"
+      # ffmpeg -i $temporary_video_file -itsoffset 0.5 -i $clean_audio_file -c:v copy -c:a aac "$output_path/$(date +%Y-%m-%d_%H-%M-%S).mkv"
+
+      # Clean temp audio files
+      rm $clean_audio_file $noisy_audio_file
+    else
+      ffmpeg -i $temporary_video_file -c:v copy -c:a copy "$output_path/$(date +%Y-%m-%d_%H-%M-%S).mkv"
+    fi
+
+    # Clean temp video file
+    rm "$temporary_video_file"
+    break
+    ;;
+  paus | p)
+    echo -e "\nPause"
+    ;;
+  help | h)
+    echo -e "\nAvailable commands are:\n" \
+      "\033[33mstop\033[0m: stop recording\n" \
+      "\033[33mhelp\033[0m: print menu help"
+    ;;
+  *)
+    echo -e "\nInvalid command."
+    ;;
+  esac
 done
 
+# Check if there is anything in the log file (indicating an error)
+if [ -s "$LOG_FILE" ]; then
+  echo "Errors were logged. Please check $LOG_FILE."
+  exit 1
+fi
